-- payment
ALTER TABLE payment ADD COLUMN confirmation_number varchar(50);
ALTER TABLE payment RENAME COLUMN name TO fee_type;
ALTER TABLE payment RENAME COLUMN number TO tx_number;

COMMENT ON COLUMN payment.confirmation_number IS 'US Bank confirmation of successful transaction.';
COMMENT ON COLUMN payment.fee_type IS 'Indicates type of fee (initial, renewal, late) associated with payment amount.';
COMMENT ON COLUMN payment.tx_number IS 'System generated transaction id for payment';

-- application
ALTER TABLE application ADD COLUMN mobile_phone VARCHAR(15);
ALTER TABLE application ADD COLUMN adverse_action_taken BOOLEAN;
ALTER TABLE application ADD COLUMN adverse_action_text TEXT;
ALTER TABLE application ADD COLUMN conviction BOOLEAN;
ALTER TABLE application ADD COLUMN conviction_text TEXT;

COMMENT ON COLUMN application.mobile_phone IS 'Mobile phone number of applicant';
COMMENT ON COLUMN application.adverse_action_taken IS 'Renewals - indicates if any adverse action was taken in past two years.';
COMMENT ON COLUMN application.adverse_action_text IS 'Renewals - describes any adverse action that was taken.';
COMMENT ON COLUMN application.conviction IS 'Renewals - indicates if applicant was charged with any conviction in past two years.';
COMMENT ON COLUMN application.conviction_text IS 'Renewals - describes any conviction applicant was charged with.';

-- attachment
ALTER TABLE attachment ADD COLUMN course_date DATE;
ALTER TABLE attachment ADD COLUMN training_presenter VARCHAR(100);

COMMENT ON COLUMN attachment.course_date IS 'Renewals - continuing education: course date associated with attachment.';
COMMENT ON COLUMN attachment.training_presenter IS 'Renewals - continuing education: trainer associated with attachment.';

-- other license
CREATE TABLE other_license (
      id VARCHAR(36) NOT NULL,
      application_id VARCHAR(36) NOT NULL,
      state VARCHAR(2) NOT NULL,
      status VARCHAR(20) NOT NULL,
      issue_date DATE NOT NULL,
      license_number VARCHAR(50) NOT NULL,
      CONSTRAINT pk_other_license PRIMARY KEY (id),
      CONSTRAINT fk_other_license_application FOREIGN KEY (application_id) REFERENCES application (id)
    );

GRANT SELECT, INSERT, UPDATE, DELETE ON other_license TO bodyart_user;

COMMENT ON TABLE other_license IS 'Other Licenses issued by other state/jurisdiction';
COMMENT ON COLUMN other_license.id IS 'Primary key - system generated';
COMMENT ON COLUMN other_license.application_id IS 'Renewal application that reported this other license';
COMMENT ON COLUMN other_license.state IS 'State issuing the license';
COMMENT ON COLUMN other_license.status IS 'The status of the license at the time of renewal';
COMMENT ON COLUMN other_license.issue_date IS 'The issue date of the license';
COMMENT ON COLUMN other_license.license_number IS 'The license number/id of the license';

alter table license add column number varchar(20);
COMMENT ON COLUMN license.number IS 'The number assigned to the license';
alter table license add column renewal_token varchar(256);
COMMENT ON COLUMN license.renewal_token IS 'The unique token generated by the system for renewals';

alter table application add column received_date date;
COMMENT ON COLUMN application.received_date IS 'The date the application was received';

alter table application add column status VARCHAR(20) NOT NULL DEFAULT 'PENDING';
COMMENT ON COLUMN application.status IS 'The status of the application';